Java servlet for sending user notifications and matches to Javascript for rendering.
googleinterns/step21-2020 pull request #13
Opened 2020-07-14 20:30 UTC by lailagamaleldin

2020-07-14 22:11 UTC, lilbroadam commented on step/src/main/java/com/google/sps/servlets/HomepageServlet.java
> +    }
Doesn't look like notificationCounter is being incremented.

2020-07-14 22:14 UTC, lilbroadam commented on step/src/main/webapp/profile.jsp
> +          });
How are the user's matches being displayed on the front end?

2020-07-14 22:17 UTC, adamsmlsn requested changes
There's some issues with this PR. When I try running it, I get database errors that aren't finding the user (the same problem we had earlier today). Can you merge master into this branch so this branch will have the database fix? Then I'll be able to check how the changes look on the front end.

2020-07-15 14:28 UTC, lilbroadam commented on step/src/main/webapp/profile.jsp
> +            renderNotifications(notifications);
Good structuring!

2020-07-15 14:37 UTC, adamsmlsn approved these changes
LGTM. When you merge, make sure the changes from [this datastore commit](https://github.com/googleinterns/step21-2020/commit/c7eeb1a18fc6aa6f11583d50ea71221499f7490f) are persistent. I think git might undo it when you merge since it's not in your branch right now.

2020-07-15 15:31 UTC, nganttran approved these changes

2020-07-15 21:46 UTC, wangding-google approved these changes

2020-07-15 22:26 UTC, merged